         
FROM 10.15
#RUN a command to build your application in the container
RUN npm i -g webpack
WORKDIR /usr/src/app
#Copy is used to copy files from docker host file system into the container
COPY package*.json ./
#install all dependecies from package.json inside container
RUN npm install
EXPOSE 8080
